jwt:
    secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArrNumberSym$^@GHJ@YUH@HQH'
logging:
    file:
        name: gts.log
    level:
        com:
            hqh: debug
        root: warn
    logback:
        rollingpolicy:
            clean-history-on-start: true
            file-name-pattern: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}
                - %msg%n'
            max-file-size: 100KB
            max-history: 14
            total-size-cap: 1MB
server:
    error:
        path: /error
    port: 9090
    servlet:
        context-path: /api/v1
spring:
    datasource:
        password: 123456
        url: jdbc:postgresql://localhost:5432/quiz
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    mail:
        host: smtp.gmail.com
        password: 
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: hoquang.huyy@gmail.com
    main:
        allow-circular-references: true
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB
    sql:
        init:
            mode: always
